### ISSUE TITLE
Fatal error: require(): Failed opening required 

### ISSUE THREAD

**Issue by Redcode456123** [smarteist/PHP2Blade#7]
Hi I am learning Laravel on my own.
I tried to follow your instructions and did the clone successfully, but when I try to convert a php file to blade I got the following error: "Fatal error: require(): Failed opening required 'C:\Users\g\PhpstormProjects\laravel_Project2\PHP2Blade\vendor\composer/../symfony/polyfill-ctype/bootstrap.php' (include_path='C:\xampp\php\PEAR') in C:\Users\g\PhpstormProjects\laravel_Project2\PHP2Blade\vendor\composer\autoload_real.php on line 69".

The command issued on the console was:
php php2blade resources/views/layouts/Job_Details_Apply.php outConverter

what am I missing or doing wrong ?

Thanks for help.

**Comment by n-a-z** [comment]
Hi.
For anyone having similar composer errors:
"PHP Warning:  require(...): failed to open stream: No such file or directory in (...)\vendor\composer\autoload_real.php on line 69"

run "composer update" command in the project directory.
